export const featureFlags = {
  strictPrdMode: true,
  showDocsPortal: false,
  showApiPlayground: false,
  showApiKeys: false,
  showTeamOnboarding: false,
  showProjects: false,
  showCliMarketing: false,
  showAdvancedIntegrations: false,
  showBetaFeatures: false,
  showResourceUsage: false,
  showProPlan: false,
  showTeamPlan: false,
  showAdvancedPricingRows: false,
} as const;
