import type { Metadata } from "next";
import { PublicPageShell } from "../_components/public-page-shell";

export const metadata: Metadata = {
  title: "CaptionLint | Privacy Policy",
  description: "Privacy Policy for CaptionLint — how we collect, use, and protect your data.",
};

const LAST_UPDATED = "May 7, 2026";

export default function PrivacyPage() {
  return (
    <PublicPageShell showAuthCta={false} mainClassName="pb-24">
      <div className="mx-auto max-w-3xl">
        <div className="mb-12">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-zinc-500">Legal</p>
          <h1 className="mb-3 text-4xl font-bold tracking-tight">Privacy Policy</h1>
          <p className="text-sm text-zinc-500">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-10 text-sm leading-7 text-zinc-400">
          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              1. Information We Collect
            </h2>
            <p className="mb-4">
              We collect information you provide directly and information generated by your use of the
              Service:
            </p>
            <ul className="space-y-2 pl-5">
              {[
                "Account data: name and email address when you register with email/password.",
                "OAuth profile data: public profile information (name, email, avatar) returned by GitHub or Google when you sign in with those providers.",
                "Caption files: the content of files you upload for linting. Files are processed and stored to provide run history. We do not use your file content for any purpose other than delivering the Service to you.",
                "Usage data: pages visited, features used, and lint run metadata (preset, finding counts, duration). Collected via PostHog analytics.",
                "Technical data: IP address, browser type, and device information for security and debugging purposes.",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="mt-0.5 text-[#22c55e]">—</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              2. How We Use Your Information
            </h2>
            <p className="mb-4">We use the information we collect to:</p>
            <ul className="space-y-2 pl-5">
              {[
                "Create and manage your account and organization.",
                "Process caption files and return lint findings and exports.",
                "Store run history so you can revisit and re-export previous results.",
                "Improve the Service through aggregate usage analytics.",
                "Send transactional emails (account confirmation, password reset) — no marketing emails without explicit opt-in.",
                "Detect and prevent fraud, abuse, and security incidents.",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="mt-0.5 text-[#22c55e]">—</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              3. Third-Party Services
            </h2>
            <p className="mb-4">
              We integrate with the following third-party services. Each has its own privacy policy:
            </p>
            <ul className="space-y-3 pl-5">
              <li className="flex gap-2">
                <span className="mt-0.5 text-[#22c55e]">—</span>
                <span>
                  <span className="font-medium text-zinc-100">GitHub OAuth</span> — used for optional
                  social sign-in. We receive your public GitHub profile (name, email, avatar). GitHub's
                  privacy policy applies to data GitHub holds.
                </span>
              </li>
              <li className="flex gap-2">
                <span className="mt-0.5 text-[#22c55e]">—</span>
                <span>
                  <span className="font-medium text-zinc-100">Google OAuth</span> — used for optional
                  social sign-in. We receive your Google profile (name, email, avatar). Google's privacy
                  policy applies to data Google holds.
                </span>
              </li>
              <li className="flex gap-2">
                <span className="mt-0.5 text-[#22c55e]">—</span>
                <span>
                  <span className="font-medium text-zinc-100">PostHog</span> — used for product
                  analytics (pageviews, feature usage). Data is pseudonymized. We use
                  <code className="mx-1 rounded bg-[#1e2e1e] px-1 py-0.5 font-mono text-xs text-zinc-300">
                    person_profiles: &quot;identified_only&quot;
                  </code>
                  so anonymous visitors are not profiled.
                </span>
              </li>
            </ul>
            <p className="mt-4">We do not sell your personal data to any third party.</p>
          </section>

          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              4. Data Storage &amp; Security
            </h2>
            <p>
              Your data is stored in a PostgreSQL database hosted in a secure environment. Passwords are
              never stored in plain text — better-auth hashes credentials before storage. Caption file
              content is stored in the database for the duration of your account. We apply
              industry-standard security practices including encrypted connections (TLS), access controls,
              and regular security reviews. No system is 100% secure; we cannot guarantee absolute
              security but we will notify you promptly of any breach that affects your data.
            </p>
          </section>

          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              5. Your Rights
            </h2>
            <p className="mb-4">Depending on your location, you may have the right to:</p>
            <ul className="space-y-2 pl-5">
              {[
                "Access the personal data we hold about you.",
                "Correct inaccurate data.",
                "Request deletion of your account and associated data.",
                "Export your data in a portable format.",
                "Opt out of analytics tracking (contact us to disable your PostHog profile).",
              ].map((item) => (
                <li key={item} className="flex gap-2">
                  <span className="mt-0.5 text-[#22c55e]">—</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mt-4">
              To exercise any of these rights, email us at{" "}
              <a href="mailto:privacy@captionlint.com" className="text-[#22c55e] hover:text-[#4be277]">
                privacy@captionlint.com
              </a>
              . We will respond within 30 days.
            </p>
          </section>

          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              6. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify registered users of
              material changes via email or an in-app notice at least 14 days before the changes take
              effect. The "last updated" date at the top of this page reflects the most recent revision.
            </p>
          </section>

          <section>
            <h2 className="mb-3 border-b border-[#353436] pb-3 text-lg font-semibold text-zinc-100">
              7. Contact
            </h2>
            <p>
              For privacy-related questions or requests, contact us at{" "}
              <a href="mailto:privacy@captionlint.com" className="text-[#22c55e] hover:text-[#4be277]">
                privacy@captionlint.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </PublicPageShell>
  );
}
